// Generated by https://quicktype.io

export interface CharacterInt {
  info: Info;
  results: Result[];
}

export interface Info {
  count: number;
  pages: number;
  next: string;
  prev: null;
}

export interface Result {
  id: number;
  name: string;
  status: Status;
  species: Species;
  type: string;
  gender: Gender;
  origin: Location;
  location: Location;
  image: string;
  episode: string[];
  url: string;
  created: string;
}

export enum Gender {
  female = 'Female',
  male = 'Male',
  unknown = 'unknown',
}

export interface Location {
  name: string;
  url: string;
}

export enum Species {
  alien = 'Alien',
  human = 'Human',
}

export enum Status {
  alive = 'Alive',
  dead = 'Dead',
  unknown = 'unknown',
}
